[package]
name = "codex-sandboxing"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[lib]
name = "codex_sandboxing"
path = "src/lib.rs"

[dependencies]
codex-network-proxy = { path = "../../../codex-wasm/wasi-network-proxy" }
codex-protocol = { path = "../protocol" }
codex-utils-absolute-path = { path = "../utils/absolute-path" }
dunce = { version = "1.0.4" }
libc = { version = "0.2.182" }
serde_json = { version = "1" }
tracing = { version = "0.1.44", features = ["log"] }
url = { version = "2" }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
tempfile = { version = "3.23.0" }
