[package]
edition = "2024"
license = "Apache-2.0"
name = "codex-plugin"
version = "0.0.0"

[lib]
doctest = false
name = "codex_plugin"
path = "src/lib.rs"

[dependencies]
codex-utils-absolute-path = { path = "../utils/absolute-path" }
codex-utils-plugins = { path = "../utils/plugins" }
thiserror = { version = "2.0.17" }
