//! Stub module — TLS/CA configuration stripped for wasip2.
//! In WASM, HTTP is handled by the host via wasi:http.
//! Auto-generated by codex-codemod. Do not edit.

use std::sync::Arc;

pub const CODEX_CA_CERT_ENV: &str = "CODEX_CA_CERTIFICATE";
pub const SSL_CERT_FILE_ENV: &str = "SSL_CERT_FILE";

#[derive(Debug, thiserror::Error)]
pub enum BuildCustomCaTransportError {
    #[error("TLS not available in WASM")]
    NotAvailable,
}

impl From<BuildCustomCaTransportError> for std::io::Error {
    fn from(e: BuildCustomCaTransportError) -> Self {
        std::io::Error::other(e)
    }
}

pub fn build_reqwest_client_with_custom_ca(
    builder: reqwest::ClientBuilder,
) -> Result<reqwest::Client, BuildCustomCaTransportError> {
    builder.build().map_err(|_| BuildCustomCaTransportError::NotAvailable)
}

/// In WASM, no custom TLS config is needed.
pub fn maybe_build_rustls_client_config_with_custom_ca()
-> Result<Option<()>, BuildCustomCaTransportError> {
    Ok(None)
}

pub fn build_reqwest_client_for_subprocess_tests(
    builder: reqwest::ClientBuilder,
) -> Result<reqwest::Client, BuildCustomCaTransportError> {
    builder.build().map_err(|_| BuildCustomCaTransportError::NotAvailable)
}
