//! Stub module — file watcher replaced with no-ops for wasip2.
//! Auto-generated by codex-codemod. Do not edit.

use std::path::PathBuf;
use std::sync::Arc;

use crate::config::Config;
use crate::skills::SkillsManager;

/// Events emitted by the file watcher.
#[derive(Debug, Clone)]
pub enum FileWatcherEvent {
    SkillsChanged { paths: Vec<PathBuf> },
}

/// File watcher — no-op in WASM (notify crate not available).
pub struct FileWatcher {
    tx: tokio::sync::broadcast::Sender<FileWatcherEvent>,
}

impl FileWatcher {
    pub(crate) fn new(_codex_home: PathBuf) -> Result<Self, Box<dyn std::error::Error>> {
        let (tx, _) = tokio::sync::broadcast::channel(16);
        Ok(Self { tx })
    }

    pub(crate) fn noop() -> Self {
        let (tx, _) = tokio::sync::broadcast::channel(16);
        Self { tx }
    }

    pub fn subscribe(&self) -> tokio::sync::broadcast::Receiver<FileWatcherEvent> {
        self.tx.subscribe()
    }

    pub(crate) fn register_config(
        self: &Arc<Self>,
        _config: &Config,
        _skills_manager: &SkillsManager,
    ) -> WatchRegistration {
        WatchRegistration
    }
}

/// Watch registration handle — no-op in WASM.
pub struct WatchRegistration;

impl Drop for WatchRegistration {
    fn drop(&mut self) {}
}
