[package]
name = "codex-app-server-protocol"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[lib]
name = "codex_app_server_protocol"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1" }
clap = { version = "4", features = ["derive"] }
codex-experimental-api-macros = { path = "../codex-experimental-api-macros" }
codex-git-utils = { path = "../git-utils" }
codex-protocol = { path = "../protocol" }
codex-shell-command = { path = "../shell-command" }
codex-utils-absolute-path = { path = "../utils/absolute-path" }
schemars = { version = "0.8.22" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_with = { version = "3.17" }
strum_macros = { version = "0.28.0" }
thiserror = { version = "2.0.17" }
rmcp = { version = "0.15.0", default-features = false, features = ["base64", "macros", "schemars", "server"] }
inventory = { version = "0.3.19" }
tracing = { version = "0.1.44" }
uuid = { version = "1", features = ["serde", "v7"] }

[dev-dependencies]
anyhow = { version = "1" }
codex-utils-cargo-bin = { path = "../utils/cargo-bin" }
pretty_assertions = { version = "1.4.1" }
similar = { version = "2.7.0" }
tempfile = { version = "3.23.0" }
