[package]
name = "codex-lmstudio"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[lib]
name = "codex_lmstudio"
path = "src/lib.rs"


[dependencies]
codex-core = { path = "../core" }
reqwest = { path = "../../../codex-wasm/wasi-reqwest" }
serde_json = "1"
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tracing = { version = "0.1.44", features = ["log"] }

[dev-dependencies]
wiremock = "0.6"
tokio = { path = "../../../codex-wasm/wasi-tokio" }
