[package]
edition = "2024"
license = "Apache-2.0"
name = "codex-core-skills"
version = "0.0.0"

[lib]
doctest = false
name = "codex_core_skills"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1" }
codex-analytics = { path = "../analytics" }
codex-app-server-protocol = { path = "../app-server-protocol" }
codex-config = { path = "../config" }
codex-instructions = { path = "../instructions" }
codex-login = { path = "../login" }
codex-otel = { path = "../../../codex-wasm/wasi-codex-otel" }
codex-protocol = { path = "../protocol" }
codex-skills = { path = "../skills" }
codex-utils-absolute-path = { path = "../utils/absolute-path" }
codex-utils-plugins = { path = "../utils/plugins" }
dirs = { version = "6" }
dunce = { version = "1.0.4" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_yaml = { version = "0.9" }
shlex = { version = "1.3.0" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
toml = { version = "0.9.5" }
tracing = { version = "0.1.44" }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
tempfile = { version = "3.23.0" }
