[package]
name = "codex-async-utils"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
async-trait = { version = "0.1.89" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tokio-util = { path = "../../../codex-wasm/wasi-tokio-util" }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
