[package]
name = "codex-app-server-test-client"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = { version = "1" }
clap = { version = "4", features = ["derive", "env"] }
codex-app-server-protocol = { path = "../app-server-protocol" }
codex-core = { path = "../core" }
codex-otel = { path = "../../../codex-wasm/wasi-codex-otel" }
codex-protocol = { path = "../protocol" }
codex-utils-cli = { path = "../utils/cli" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tracing = { version = "0.1.44" }
tracing-subscriber = { version = "0.3.22" }
tungstenite = { path = "../../../codex-wasm/wasi-tungstenite" }
url = { version = "2" }
uuid = { version = "1", features = ["v4"] }
