[package]
edition = "2024"
license = "Apache-2.0"
name = "codex-protocol"
version = "0.0.0"

[lib]
name = "codex_protocol"
path = "src/lib.rs"

[dependencies]
codex-execpolicy = { path = "../execpolicy" }
codex-git = { path = "../utils/git" }
codex-utils-absolute-path = { path = "../utils/absolute-path" }
codex-utils-image = { path = "../utils/image" }
icu_decimal = { version = "2.1" }
icu_locale_core = { version = "2.1" }
icu_provider = { version = "2.1", features = ["sync"] }
quick-xml = { version = "0.38.4", features = ["serialize"] }
schemars = { version = "0.8.22" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_with = { version = "3.17", features = ["macros", "base64"] }
strum = { version = "0.27.2" }
strum_macros = { version = "0.28.0" }
sys-locale = { version = "0.3.2" }
tracing = { version = "0.1.44" }
uuid = { version = "1", features = ["serde", "v7", "v4"] }

[dev-dependencies]
anyhow = { version = "1" }
pretty_assertions = { version = "1.4.1" }
tempfile = { version = "3.23.0" }

[package.metadata.cargo-shear]
# Required because:
# `icu_provider`: contains a required `sync` feature for `icu_decimal`
# `strum`: as strum_macros in non-nightly builds
ignored = ["icu_provider", "strum"]
