[package]
name = "codex-utils-cache"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
lru = { version = "0.16.3" }
sha1 = { version = "0.10.6" }
tokio = { path = "../../../../codex-wasm/wasi-tokio" }

[dev-dependencies]
tokio = { path = "../../../../codex-wasm/wasi-tokio" }
