[package]
name = "codex-exec-server"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[lib]
doctest = false

[[bin]]
name = "codex-exec-server"
path = "src/bin/codex-exec-server.rs"

[dependencies]
async-trait = { version = "0.1.89" }
base64 = { version = "0.22.1" }
codex-app-server-protocol = { path = "../app-server-protocol" }
codex-utils-absolute-path = { path = "../utils/absolute-path" }
codex-utils-pty = { path = "../utils/pty" }
futures = { version = "0.3", default-features = false , features = ["alloc"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
thiserror = { version = "2.0.17" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tracing = { version = "0.1.44" }

[dev-dependencies]
anyhow = { version = "1" }
codex-utils-cargo-bin = { path = "../utils/cargo-bin" }
pretty_assertions = { version = "1.4.1" }
tempfile = { version = "3.23.0" }
test-case = "3.3.1"
