[package]
edition = "2024"
license = "Apache-2.0"
name = "codex-mcp"
version = "0.0.0"

[lib]
name = "codex_mcp"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1" }
async-channel = { version = "2.3.1" }
codex-async-utils = { path = "../async-utils" }
codex-config = { path = "../config" }
codex-login = { path = "../login" }
codex-otel = { path = "../../../codex-wasm/wasi-codex-otel" }
codex-plugin = { path = "../plugin" }
codex-protocol = { path = "../protocol" }
codex-rmcp-client = { path = "../../../codex-wasm/wasi-rmcp-client" }
codex-utils-plugins = { path = "../utils/plugins" }
futures = { version = "0.3", default-features = false , features = ["alloc"] }
regex-lite = { version = "0.1.8" }
rmcp = { version = "0.15.0", default-features = false, features = ["base64", "macros", "schemars", "server"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
sha1 = { version = "0.10.6" }
thiserror = { version = "2.0.17" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tokio-util = { path = "../../../codex-wasm/wasi-tokio-util" }
tracing = { version = "0.1.44" }
url = { version = "2" }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
rmcp = { version = "0.15.0", default-features = false, features = ["base64", "macros", "schemars", "server"] }
tempfile = { version = "3.23.0" }
