[package]
edition = "2024"
license = "Apache-2.0"
name = "codex-instructions"
version = "0.0.0"

[lib]
doctest = false
name = "codex_instructions"
path = "src/lib.rs"

[dependencies]
codex-protocol = { path = "../protocol" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
