[package]
build = "build.rs"
edition = "2024"
license = "Apache-2.0"
name = "codex-windows-sandbox"
version = "0.0.0"

[lib]
name = "codex_windows_sandbox"
path = "src/lib.rs"

[[bin]]
name = "codex-windows-sandbox-setup"
path = "src/bin/setup_main.rs"

[[bin]]
name = "codex-command-runner"
path = "src/bin/command_runner.rs"

[dependencies]
anyhow = "1.0"
base64 = { version = "0.22.1" }
chrono = { version = "0.4.42", default-features = false, features = [
    "clock",
    "std",
] }
codex-utils-pty = { path = "../../../codex-wasm/wasi-pty" }
codex-utils-absolute-path = { path = "../utils/absolute-path" }
codex-utils-string = { path = "../utils/string" }
dunce = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"
tokio = { path = "../../../codex-wasm/wasi-tokio" }
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_WindowsFirewall",
    "Win32_System_Com",
    "Win32_System_Variant",
] }

[dependencies.codex-protocol]
package = "codex-protocol"
path = "../protocol"

[dependencies.rand]
default-features = false
features = ["std", "small_rng"]
version = "0.8"

[dependencies.dirs-next]
version = "2.0"

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }

[build-dependencies]
winres = "0.1"

[package.metadata.cargo-shear]
ignored = ["codex-utils-pty", "tokio"]
