//! Stub module — TypeScript export stripped for wasip2.
//! Auto-generated by codex-codemod. Do not edit.

use anyhow::Result;
use std::path::Path;

pub const GENERATED_TS_HEADER: &str = "";

#[derive(Default)]
pub struct GenerateTsOptions {
    pub experimental_api: bool,
}

pub struct GeneratedSchema {
    pub name: String,
    pub schema: serde_json::Value,
}

pub fn generate_types(_out_dir: &Path, _prettier: Option<&Path>) -> Result<()> { Ok(()) }
pub fn generate_ts(_out_dir: &Path, _prettier: Option<&Path>) -> Result<()> { Ok(()) }
pub fn generate_ts_with_options(_out_dir: &Path, _prettier: Option<&Path>, _options: GenerateTsOptions) -> Result<()> { Ok(()) }
pub fn generate_json(_out_dir: &Path) -> Result<()> { Ok(()) }
pub fn generate_internal_json_schema(_out_dir: &Path) -> Result<()> { Ok(()) }
pub fn generate_json_with_experimental(_out_dir: &Path, _experimental_api: bool) -> Result<()> { Ok(()) }
pub fn filter_experimental_ts_tree(_tree: &mut std::collections::BTreeMap<std::path::PathBuf, Vec<u8>>) {}
pub fn generate_index_ts_tree(_tree: &std::collections::BTreeMap<std::path::PathBuf, Vec<u8>>) -> std::collections::BTreeMap<std::path::PathBuf, Vec<u8>> { std::collections::BTreeMap::new() }

pub(crate) fn write_json_schema<T>(_out_dir: &Path, name: &str) -> Result<GeneratedSchema>
where T: schemars::JsonSchema {
    Ok(GeneratedSchema { name: name.to_string(), schema: serde_json::Value::Null })
}
