//! Stub module — ts-rs schema fixtures stripped for wasip2.
//! Auto-generated by codex-codemod. Do not edit.

use anyhow::Result;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

#[derive(Clone, Copy, Debug, Default)]
pub struct SchemaFixtureOptions {
    pub experimental_api: bool,
}

pub fn read_schema_fixture_tree(_schema_root: &Path) -> Result<BTreeMap<PathBuf, Vec<u8>>> {
    Ok(BTreeMap::new())
}

pub fn read_schema_fixture_subtree(
    _schema_root: &Path,
    _options: SchemaFixtureOptions,
) -> Result<BTreeMap<PathBuf, Vec<u8>>> {
    Ok(BTreeMap::new())
}

pub fn generate_typescript_schema_fixture_subtree_for_tests() -> Result<BTreeMap<PathBuf, Vec<u8>>> {
    Ok(BTreeMap::new())
}

pub fn write_schema_fixtures(_schema_root: &Path, _prettier: Option<&Path>) -> Result<()> {
    Ok(())
}

pub fn write_schema_fixtures_with_options(
    _schema_root: &Path,
    _prettier: Option<&Path>,
    _options: SchemaFixtureOptions,
) -> Result<()> {
    Ok(())
}
