[package]
name = "codex-utils-sandbox-summary"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
codex-core = { path = "../../core" }
codex-model-provider-info = { path = "../../model-provider-info" }
codex-protocol = { path = "../../protocol" }

[dev-dependencies]
codex-utils-absolute-path = { path = "../absolute-path" }
pretty_assertions = { version = "1.4.1" }
