[package]
name = "codex-exec"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[[bin]]
name = "codex-exec"
path = "src/main.rs"

[lib]
name = "codex_exec"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1" }
clap = { version = "4", features = ["derive"] }
codex-arg0 = { path = "../arg0" }
codex-app-server-protocol = { path = "../app-server-protocol" }
codex-core = { path = "../core" }
codex-otel = { path = "../../../codex-wasm/wasi-codex-otel" }
codex-protocol = { path = "../protocol" }
codex-utils-absolute-path = { path = "../utils/absolute-path" }
codex-utils-cli = { path = "../utils/cli" }
codex-utils-elapsed = { path = "../utils/elapsed" }
codex-utils-sandbox-summary = { path = "../utils/sandbox-summary" }
owo-colors = { version = "4.3.0" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
shlex = { version = "1.3.0" }
supports-color = { version = "3.0.2" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
uuid = { version = "1" }


[dev-dependencies]
assert_cmd = { version = "2" }
codex-apply-patch = { path = "../apply-patch" }
codex-utils-cargo-bin = { path = "../utils/cargo-bin" }
libc = { version = "0.2.182" }
opentelemetry = { version = "0.31.0" }
opentelemetry_sdk = { version = "0.31.0" }
predicates = { version = "3" }
pretty_assertions = { version = "1.4.1" }
rmcp = { version = "0.15.0", default-features = false }
tempfile = { version = "3.23.0" }
tracing-opentelemetry = { version = "0.32.0" }
uuid = { version = "1" }
walkdir = { version = "2.5.0" }
wiremock = { version = "0.6" }
