[package]
edition = "2024"
license = "Apache-2.0"
name = "codex-models-manager"
version = "0.0.0"

[lib]
doctest = false
name = "codex_models_manager"
path = "src/lib.rs"

[dependencies]
chrono = { version = "0.4.43", features = ["serde"] }
codex-api = { path = "../codex-api" }
codex-app-server-protocol = { path = "../app-server-protocol" }
codex-collaboration-mode-templates = { path = "../collaboration-mode-templates" }
codex-config = { path = "../config" }
codex-login = { path = "../login" }
codex-model-provider-info = { path = "../model-provider-info" }
codex-otel = { path = "../../../codex-wasm/wasi-codex-otel" }
codex-protocol = { path = "../protocol" }
codex-response-debug-context = { path = "../response-debug-context" }
codex-utils-output-truncation = { path = "../utils/output-truncation" }
codex-utils-template = { path = "../utils/template" }
http = { version = "1.3.1" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tracing = { version = "0.1.44", features = ["log"] }
codex-feedback = { path = "../../../codex-wasm/wasi-codex-feedback" }

[dev-dependencies]
base64 = { version = "0.22.1" }
codex-utils-absolute-path = { path = "../utils/absolute-path" }
pretty_assertions = { version = "1.4.1" }
serde_json = { version = "1" }
tempfile = { version = "3.23.0" }
tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3.22" }
wiremock = { version = "0.6" }
codex-feedback = { path = "../../../codex-wasm/wasi-codex-feedback" }
