[package]
name = "codex-cloud-tasks"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[lib]
name = "codex_cloud_tasks"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1" }
base64 = { version = "0.22.1" }
chrono = { version = "0.4.43", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
codex-client = { path = "../codex-client" }
codex-core = { path = "../core" }
codex-login = { path = "../login" }
codex-utils-cli = { path = "../utils/cli" }
crossterm = { path = "../../../codex-wasm/wasi-crossterm" }
ratatui = { version = "0.29.0" }
reqwest = { path = "../../../codex-wasm/wasi-reqwest" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tokio-stream = { version = "0.1.18" }
tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
unicode-width = { version = "0.2" }
owo-colors = { version = "4.3.0", features = ["supports-colors"] }
supports-color = { version = "3.0.2" }
async-trait = { version = "0.1.89" }

[dev-dependencies]
async-trait = { version = "0.1.89" }
pretty_assertions = { version = "1.4.1" }
