[package]
edition = "2024"
license = "Apache-2.0"
name = "codex-hooks"
version = "0.0.0"

[lib]
doctest = false
name = "codex_hooks"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1" }
chrono = { version = "0.4.43", features = ["serde"] }
codex-config = { path = "../config" }
codex-protocol = { path = "../protocol" }
futures = { version = "0.3", default-features = false , features = ["alloc"] }
regex = { version = "1.12.3" }
schemars = { version = "0.8.22" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
tempfile = { version = "3.23.0" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
