[package]
edition = "2024"
license = "Apache-2.0"
name = "codex-skills"
version = "0.0.0"
build = "build.rs"

[lib]
doctest = false
name = "codex_skills"
path = "src/lib.rs"

[dependencies]
codex-utils-absolute-path = { path = "../utils/absolute-path" }
include_dir = { version = "0.7.4" }
thiserror = { version = "2.0.17" }
