//! Stub module — archive extraction stripped for wasip2.
//! Auto-generated by codex-codemod. Do not edit.

use std::path::{Path, PathBuf};
use crate::PackageManagerError;

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, PartialEq, Eq)]
pub struct PackageReleaseArchive {
    pub archive: String,
    pub sha256: String,
    pub format: ArchiveFormat,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<u64>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ArchiveFormat {
    TarGz,
    Zip,
}

impl PackageReleaseArchive {
    pub(crate) fn extract_to(
        &self,
        _archive_bytes: &[u8],
        _dest: &Path,
    ) -> Result<PathBuf, PackageManagerError> {
        Err(PackageManagerError::ArchiveExtraction(
            "archive extraction not available in WASM".to_string(),
        ))
    }
}

pub(crate) fn detect_single_package_root(
    extraction_root: &Path,
) -> Result<PathBuf, PackageManagerError> {
    Ok(extraction_root.to_path_buf())
}

pub(crate) fn verify_archive_size(
    _bytes: &[u8],
    _expected: Option<u64>,
) -> Result<(), PackageManagerError> {
    Ok(())
}

pub(crate) fn verify_sha256(_bytes: &[u8], _expected: &str) -> Result<(), PackageManagerError> {
    Ok(())
}

pub(crate) fn extract_archive(
    _archive_path: &Path,
    _destination: &Path,
    _format: ArchiveFormat,
) -> Result<(), PackageManagerError> {
    Err(PackageManagerError::ArchiveExtraction(
        "archive extraction not available in WASM".to_string(),
    ))
}
