//! Stub module — keyring replaced with in-memory store for wasip2.
//! Auto-generated by codex-codemod. Do not edit.

use std::collections::HashMap;
use std::error::Error;
use std::fmt;
use std::fmt::Debug;
use std::sync::{Arc, Mutex, PoisonError};

#[derive(Debug)]
pub enum CredentialStoreError {
    Other(String),
}

impl CredentialStoreError {
    pub fn message(&self) -> String {
        match self {
            Self::Other(s) => s.clone(),
        }
    }

    pub fn into_error(self) -> Box<dyn Error> {
        Box::new(self)
    }
}

impl fmt::Display for CredentialStoreError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Other(s) => write!(f, "{s}"),
        }
    }
}

impl Error for CredentialStoreError {}

/// Shared credential store abstraction.
pub trait KeyringStore: Debug + Send + Sync {
    fn load(&self, service: &str, account: &str) -> Result<Option<String>, CredentialStoreError>;
    fn save(&self, service: &str, account: &str, value: &str) -> Result<(), CredentialStoreError>;
    fn delete(&self, service: &str, account: &str) -> Result<bool, CredentialStoreError>;
}

/// In-memory keyring store for WASM (no platform keychain available).
/// Uses interior mutability with a lazy-initialized Mutex so the struct
/// can be constructed as a unit struct: `DefaultKeyringStore` (matching original API).
#[derive(Debug)]
pub struct DefaultKeyringStore;

/// Backing store (global for simplicity in WASM single-threaded context).
static STORE: std::sync::LazyLock<Mutex<HashMap<String, String>>> =
    std::sync::LazyLock::new(|| Mutex::new(HashMap::new()));

impl KeyringStore for DefaultKeyringStore {
    fn load(&self, service: &str, account: &str) -> Result<Option<String>, CredentialStoreError> {
        let guard = STORE.lock().unwrap_or_else(PoisonError::into_inner);
        Ok(guard.get(&format!("{service}:{account}")).cloned())
    }

    fn save(&self, service: &str, account: &str, value: &str) -> Result<(), CredentialStoreError> {
        let mut guard = STORE.lock().unwrap_or_else(PoisonError::into_inner);
        guard.insert(format!("{service}:{account}"), value.to_string());
        Ok(())
    }

    fn delete(&self, service: &str, account: &str) -> Result<bool, CredentialStoreError> {
        let mut guard = STORE.lock().unwrap_or_else(PoisonError::into_inner);
        Ok(guard.remove(&format!("{service}:{account}")).is_some())
    }
}

pub mod tests {
    use super::*;

    #[derive(Default, Clone, Debug)]
    pub struct MockKeyringStore {
        data: Arc<Mutex<HashMap<String, String>>>,
    }

    impl MockKeyringStore {
        pub fn saved_value(&self, account: &str) -> Option<String> {
            let guard = self.data.lock().unwrap_or_else(PoisonError::into_inner);
            guard.get(account).cloned()
        }
    }

    impl KeyringStore for MockKeyringStore {
        fn load(&self, _service: &str, account: &str) -> Result<Option<String>, CredentialStoreError> {
            let guard = self.data.lock().unwrap_or_else(PoisonError::into_inner);
            Ok(guard.get(account).cloned())
        }

        fn save(&self, _service: &str, account: &str, value: &str) -> Result<(), CredentialStoreError> {
            let mut guard = self.data.lock().unwrap_or_else(PoisonError::into_inner);
            guard.insert(account.to_string(), value.to_string());
            Ok(())
        }

        fn delete(&self, _service: &str, account: &str) -> Result<bool, CredentialStoreError> {
            let mut guard = self.data.lock().unwrap_or_else(PoisonError::into_inner);
            Ok(guard.remove(account).is_some())
        }
    }
}
