[package]
name = "codex-mcp-server"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[[bin]]
name = "codex-mcp-server"
path = "src/main.rs"

[lib]
name = "codex_mcp_server"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1" }
codex-arg0 = { path = "../arg0" }
codex-config = { path = "../config" }
codex-core = { path = "../core" }
codex-exec-server = { path = "../../../codex-wasm/wasi-exec-server" }
codex-features = { path = "../features" }
codex-login = { path = "../login" }
codex-models-manager = { path = "../models-manager" }
codex-protocol = { path = "../protocol" }
codex-utils-cli = { path = "../utils/cli" }
codex-utils-json-to-toml = { path = "../utils/json-to-toml" }
rmcp = { version = "0.15.0", default-features = false }
schemars = { version = "0.8.22" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
shlex = { version = "1.3.0" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }

[dev-dependencies]
codex-shell-command = { path = "../shell-command" }
os_info = { path = "../../../codex-wasm/wasi-os-info" }
pretty_assertions = { version = "1.4.1" }
tempfile = { version = "3.23.0" }
wiremock = { version = "0.6" }
