[package]
name = "codex-login"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
async-trait = { version = "0.1.89" }
base64 = { version = "0.22.1" }
chrono = { version = "0.4.43", features = ["serde"] }
codex-app-server-protocol = { path = "../app-server-protocol" }
codex-client = { path = "../codex-client" }
codex-config = { path = "../config" }
codex-keyring-store = { path = "../keyring-store" }
codex-protocol = { path = "../protocol" }
codex-terminal-detection = { path = "../terminal-detection" }
once_cell = { version = "1.20.2" }
os_info = { path = "../../../codex-wasm/wasi-os-info" }
rand = { version = "0.9" }
reqwest = { path = "../../../codex-wasm/wasi-reqwest" }
schemars = { version = "0.8.22" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
sha2 = { version = "0.10" }
thiserror = { version = "2.0.17" }
tiny_http = { version = "0.12" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tracing = { version = "0.1.44" }
url = { version = "2" }
urlencoding = { version = "2.1" }
webbrowser = { version = "1.0" }

[dev-dependencies]
anyhow = { version = "1" }
pretty_assertions = { version = "1.4.1" }
regex-lite = { version = "0.1.8" }
serial_test = { version = "3.2.0" }
tempfile = { version = "3.23.0" }
wiremock = { version = "0.6" }
