[package]
name = "codex-cloud-requirements"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
async-trait = { version = "0.1.89" }
base64 = { version = "0.22.1" }
chrono = { version = "0.4.43", features = ["serde"] }
codex-backend-client = { path = "../../../codex-wasm/wasi-codex-backend-client" }
codex-config = { path = "../config" }
codex-core = { path = "../core" }
codex-login = { path = "../login" }
codex-otel = { path = "../../../codex-wasm/wasi-codex-otel" }
codex-protocol = { path = "../protocol" }
hmac = "0.12.1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
sha2 = { version = "0.10" }
thiserror = { version = "2.0.17" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
toml = { version = "0.9.5" }
tracing = { version = "0.1.44" }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
tempfile = { version = "3.23.0" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
