[package]
edition = "2024"
license = "Apache-2.0"
name = "codex-tools"
version = "0.0.0"

[dependencies]
codex-app-server-protocol = { path = "../app-server-protocol" }
codex-code-mode = { path = "../code-mode" }
codex-features = { path = "../features" }
codex-protocol = { path = "../protocol" }
codex-utils-absolute-path = { path = "../utils/absolute-path" }
codex-utils-pty = { path = "../../../codex-wasm/wasi-pty" }
rmcp = { version = "0.15.0", default-features = false, features = ["base64", "macros", "schemars", "server"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tracing = { version = "0.1.44" }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
