//! Stub module — rmcp-client replaced with stubs for wasip2.
//! Process spawning, OAuth, and browser interactions are not available in WASM.
//! Auto-generated by codex-codemod. Do not edit.

#![allow(dead_code, unused_variables, unused_imports)]

use std::collections::HashMap;
use std::ffi::OsString;
use std::io;
use std::path::PathBuf;
use std::time::Duration;

use anyhow::Result;
use futures::future::BoxFuture;
use serde::{Deserialize, Serialize};

// Re-export types from rmcp model (codex-core uses these via us AND directly)
pub use rmcp::model::ElicitationAction;
pub use rmcp::model::CreateElicitationRequestParams;

// Re-export from codex_protocol
pub use codex_protocol::protocol::McpAuthStatus;

/// Type alias matching upstream.
pub type Elicitation = CreateElicitationRequestParams;

/// Callback for handling elicitation requests.
pub type SendElicitation = Box<
    dyn Fn(rmcp::model::RequestId, Elicitation) -> BoxFuture<'static, Result<ElicitationResponse>>
        + Send
        + Sync,
>;

/// Response to an elicitation request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ElicitationResponse {
    pub action: ElicitationAction,
    pub content: Option<serde_json::Value>,
    #[serde(rename = "_meta")]
    pub meta: Option<serde_json::Value>,
}

/// Tool with connector metadata.
pub struct ToolWithConnectorId {
    pub tool: rmcp::model::Tool,
    pub connector_id: Option<String>,
    pub connector_name: Option<String>,
    pub connector_description: Option<String>,
}

/// Result of listing tools with connector IDs.
pub struct ListToolsWithConnectorIdResult {
    pub next_cursor: Option<String>,
    pub tools: Vec<ToolWithConnectorId>,
}

/// OAuth credential storage mode.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
pub enum OAuthCredentialsStoreMode {
    #[default]
    Auto,
    File,
    Keyring,
}

/// Stored OAuth tokens.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoredOAuthTokens {
    pub server_name: String,
    pub url: String,
    pub client_id: String,
    pub token_response: serde_json::Value,
    pub expires_at: Option<u64>,
}

/// Wrapped OAuth token response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WrappedOAuthTokenResponse(pub serde_json::Value);

/// OAuth provider error.
#[derive(Debug)]
pub struct OAuthProviderError {
    pub error: Option<String>,
    pub error_description: Option<String>,
}

impl OAuthProviderError {
    pub fn new(error: Option<String>, error_description: Option<String>) -> Self {
        Self { error, error_description }
    }
}

impl std::fmt::Display for OAuthProviderError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "OAuth error: {:?}", self.error)
    }
}

impl std::error::Error for OAuthProviderError {}

/// Handle for an in-progress OAuth login.
pub struct OauthLoginHandle {
    authorization_url: String,
}

impl OauthLoginHandle {
    pub fn authorization_url(&self) -> &str {
        &self.authorization_url
    }

    pub fn into_parts(self) -> (String, tokio::sync::oneshot::Receiver<Result<()>>) {
        let (_tx, rx) = tokio::sync::oneshot::channel();
        (self.authorization_url, rx)
    }

    pub async fn wait(self) -> Result<()> {
        anyhow::bail!("OAuth login not available in WASM")
    }
}

/// OAuth discovery result.
#[derive(Debug, Clone)]
pub struct StreamableHttpOAuthDiscovery {
    pub scopes_supported: Option<Vec<String>>,
}

/// Save OAuth tokens — no-op in WASM.
pub fn save_oauth_tokens(
    _server_name: &str,
    _tokens: &StoredOAuthTokens,
    _store_mode: OAuthCredentialsStoreMode,
) -> Result<()> {
    Ok(())
}

/// Delete OAuth tokens — no-op in WASM.
pub fn delete_oauth_tokens(
    _server_name: &str,
    _url: &str,
    _store_mode: OAuthCredentialsStoreMode,
) -> Result<bool> {
    Ok(false)
}

/// Perform OAuth login — not available in WASM.
pub async fn perform_oauth_login(
    _server_name: &str,
    _server_url: &str,
    _store_mode: OAuthCredentialsStoreMode,
    _http_headers: Option<HashMap<String, String>>,
    _env_http_headers: Option<HashMap<String, String>>,
    _scopes: &[String],
    _oauth_resource: Option<&str>,
    _callback_port: Option<u16>,
    _callback_url: Option<&str>,
) -> Result<()> {
    anyhow::bail!("OAuth login not available in WASM")
}

/// Perform OAuth login returning URL — not available in WASM.
pub async fn perform_oauth_login_return_url(
    _server_name: &str,
    _server_url: &str,
    _store_mode: OAuthCredentialsStoreMode,
    _http_headers: Option<HashMap<String, String>>,
    _env_http_headers: Option<HashMap<String, String>>,
    _scopes: &[String],
    _oauth_resource: Option<&str>,
    _timeout_secs: Option<i64>,
    _callback_port: Option<u16>,
    _callback_url: Option<&str>,
) -> Result<OauthLoginHandle> {
    anyhow::bail!("OAuth login not available in WASM")
}

/// Determine auth status — returns Unsupported in WASM.
pub async fn determine_streamable_http_auth_status(
    _server_name: &str,
    _url: &str,
    _bearer_token_env_var: Option<&str>,
    _http_headers: Option<HashMap<String, String>>,
    _env_http_headers: Option<HashMap<String, String>>,
    _store_mode: OAuthCredentialsStoreMode,
) -> Result<McpAuthStatus> {
    Ok(McpAuthStatus::Unsupported)
}

/// Check if OAuth is supported — always false in WASM.
pub async fn supports_oauth_login(_url: &str) -> Result<bool> {
    Ok(false)
}

/// Discover OAuth configuration — returns None in WASM.
pub async fn discover_streamable_http_oauth(
    _url: &str,
    _http_headers: Option<HashMap<String, String>>,
    _env_http_headers: Option<HashMap<String, String>>,
) -> Result<Option<StreamableHttpOAuthDiscovery>> {
    Ok(None)
}

/// MCP client — stub for WASM.
pub struct RmcpClient;

impl RmcpClient {
    /// Create a stdio MCP client — not available in WASM.
    pub async fn new_stdio_client(
        _program: OsString,
        _args: Vec<OsString>,
        _env: Option<HashMap<String, String>>,
        _env_vars: &[String],
        _cwd: Option<PathBuf>,
    ) -> io::Result<Self> {
        Err(io::Error::new(
            io::ErrorKind::Unsupported,
            "stdio MCP client not available in WASM",
        ))
    }

    /// Create a streamable HTTP MCP client — stub.
    pub async fn new_streamable_http_client(
        _server_name: &str,
        _url: &str,
        _bearer_token: Option<String>,
        _http_headers: Option<HashMap<String, String>>,
        _env_http_headers: Option<HashMap<String, String>>,
        _store_mode: OAuthCredentialsStoreMode,
    ) -> Result<Self> {
        anyhow::bail!("streamable HTTP MCP client not yet implemented for WASM")
    }

    /// Initialize the MCP connection.
    pub async fn initialize(
        &self,
        _params: rmcp::model::InitializeRequestParams,
        _timeout: Option<Duration>,
        _send_elicitation: SendElicitation,
    ) -> Result<rmcp::model::InitializeResult> {
        anyhow::bail!("MCP client not available in WASM")
    }

    /// List available tools.
    pub async fn list_tools(
        &self,
        _params: Option<rmcp::model::PaginatedRequestParams>,
        _timeout: Option<Duration>,
    ) -> Result<rmcp::model::ListToolsResult> {
        anyhow::bail!("MCP client not available in WASM")
    }

    /// List tools with connector IDs.
    pub async fn list_tools_with_connector_ids(
        &self,
        _params: Option<rmcp::model::PaginatedRequestParams>,
        _timeout: Option<Duration>,
    ) -> Result<ListToolsWithConnectorIdResult> {
        anyhow::bail!("MCP client not available in WASM")
    }

    /// List available resources.
    pub async fn list_resources(
        &self,
        _params: Option<rmcp::model::PaginatedRequestParams>,
        _timeout: Option<Duration>,
    ) -> Result<rmcp::model::ListResourcesResult> {
        anyhow::bail!("MCP client not available in WASM")
    }

    /// List resource templates.
    pub async fn list_resource_templates(
        &self,
        _params: Option<rmcp::model::PaginatedRequestParams>,
        _timeout: Option<Duration>,
    ) -> Result<rmcp::model::ListResourceTemplatesResult> {
        anyhow::bail!("MCP client not available in WASM")
    }

    /// Read a resource.
    pub async fn read_resource(
        &self,
        _params: rmcp::model::ReadResourceRequestParams,
        _timeout: Option<Duration>,
    ) -> Result<rmcp::model::ReadResourceResult> {
        anyhow::bail!("MCP client not available in WASM")
    }

    /// Call a tool.
    pub async fn call_tool(
        &self,
        _name: String,
        _arguments: Option<serde_json::Value>,
        _meta: Option<serde_json::Value>,
        _timeout: Option<Duration>,
    ) -> Result<rmcp::model::CallToolResult> {
        anyhow::bail!("MCP client not available in WASM")
    }

    /// Send a custom notification.
    pub async fn send_custom_notification(
        &self,
        _method: &str,
        _params: Option<serde_json::Value>,
    ) -> Result<()> {
        anyhow::bail!("MCP client not available in WASM")
    }

    /// Send a custom request.
    pub async fn send_custom_request(
        &self,
        _method: &str,
        _params: Option<serde_json::Value>,
    ) -> Result<serde_json::Value> {
        anyhow::bail!("MCP client not available in WASM")
    }
}
