//! rquickjs-based code-mode runtime for wasm32-wasip2.
//! Auto-generated by codex-codemod. Do not edit.
//!
//! Replaces the V8 runtime stub with a working QuickJS implementation.
//! All type definitions are preserved; spawn_runtime() now creates a
//! real JavaScript execution environment.

use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};

use serde_json::Value as JsonValue;
use tokio::sync::mpsc;

use crate::description::{normalize_code_mode_identifier, ToolDefinition};
use crate::response::{FunctionCallOutputContentItem, ImageDetail};

use wasi_code_runtime::rquickjs;
use wasi_code_runtime::rquickjs::{
    context::EvalOptions, CatchResultExt, Function, Object, Value,
};

pub const DEFAULT_EXEC_YIELD_TIME_MS: u64 = 10_000;
pub const DEFAULT_WAIT_YIELD_TIME_MS: u64 = 10_000;
pub const DEFAULT_MAX_OUTPUT_TOKENS_PER_EXEC_CALL: usize = 10_000;

#[derive(Clone, Debug)]
pub struct ExecuteRequest {
    pub tool_call_id: String,
    pub enabled_tools: Vec<ToolDefinition>,
    pub source: String,
    pub stored_values: HashMap<String, JsonValue>,
    pub yield_time_ms: Option<u64>,
    pub max_output_tokens: Option<usize>,
}

#[derive(Clone, Debug)]
pub struct WaitRequest {
    pub cell_id: String,
    pub yield_time_ms: u64,
    pub terminate: bool,
}

#[derive(Debug, PartialEq)]
pub enum RuntimeResponse {
    Yielded {
        cell_id: String,
        content_items: Vec<FunctionCallOutputContentItem>,
    },
    Terminated {
        cell_id: String,
        content_items: Vec<FunctionCallOutputContentItem>,
    },
    Result {
        cell_id: String,
        content_items: Vec<FunctionCallOutputContentItem>,
        stored_values: HashMap<String, JsonValue>,
        error_text: Option<String>,
    },
}

#[derive(Debug)]
pub(crate) enum TurnMessage {
    ToolCall {
        cell_id: String,
        id: String,
        name: String,
        input: Option<JsonValue>,
    },
    Notify {
        cell_id: String,
        call_id: String,
        text: String,
    },
}

#[derive(Debug)]
pub(crate) enum RuntimeCommand {
    ToolResponse { id: String, result: JsonValue },
    ToolError { id: String, error_text: String },
    Terminate,
}

#[derive(Debug)]
pub(crate) enum RuntimeEvent {
    Started,
    ContentItem(FunctionCallOutputContentItem),
    YieldRequested,
    ToolCall {
        id: String,
        name: String,
        input: Option<JsonValue>,
    },
    Notify {
        call_id: String,
        text: String,
    },
    Result {
        stored_values: HashMap<String, JsonValue>,
        error_text: Option<String>,
    },
}

/// Runtime handle backed by an atomic terminate flag.
#[derive(Clone)]
pub(crate) struct RuntimeHandle {
    terminate_flag: Arc<AtomicBool>,
}

impl RuntimeHandle {
    pub fn terminate_execution(&self) {
        self.terminate_flag.store(true, Ordering::SeqCst);
    }
}

// ---------------------------------------------------------------------------
// Shared runtime state accessible from JS global functions
// ---------------------------------------------------------------------------

struct RuntimeState {
    event_tx: mpsc::UnboundedSender<RuntimeEvent>,
    tool_call_id: String,
    stored_values: HashMap<String, JsonValue>,
    next_tool_call_id: u64,
    /// Set of pending tool call IDs (resolvers are stored JS-side in __toolResolvers).
    pending_tool_ids: std::collections::HashSet<String>,
    exit_requested: bool,
}

type SharedState = Arc<Mutex<RuntimeState>>;

// ---------------------------------------------------------------------------
// Send wrapper for QuickJS types (safe in single-threaded WASM)
// ---------------------------------------------------------------------------

/// Wrapper to make QuickJS types usable in wasi-tokio's `spawn()` which
/// requires `Send`. This is sound because wasm32-wasip2 is single-threaded;
/// no data race can occur.
struct SendWrapper<T>(T);

// SAFETY: wasm32-wasip2 is single-threaded. The Runtime and Context are only
// ever accessed from the same (and only) thread.
unsafe impl<T> Send for SendWrapper<T> {}

// ---------------------------------------------------------------------------
// spawn_runtime — public entry point matching the service.rs contract
// ---------------------------------------------------------------------------

pub(crate) fn spawn_runtime(
    request: ExecuteRequest,
    event_tx: mpsc::UnboundedSender<RuntimeEvent>,
) -> Result<(std::sync::mpsc::Sender<RuntimeCommand>, RuntimeHandle), String> {
    let (command_tx, command_rx) = std::sync::mpsc::channel();
    let terminate_flag = Arc::new(AtomicBool::new(false));
    let handle = RuntimeHandle {
        terminate_flag: terminate_flag.clone(),
    };

    let command_rx = SendWrapper(command_rx);
    tokio::spawn(async move {
        let command_rx = command_rx.0;
        run_runtime(request, event_tx, command_rx, terminate_flag);
    });

    Ok((command_tx, handle))
}

// ---------------------------------------------------------------------------
// run_runtime — drives the QuickJS engine synchronously
// ---------------------------------------------------------------------------

fn run_runtime(
    request: ExecuteRequest,
    event_tx: mpsc::UnboundedSender<RuntimeEvent>,
    command_rx: std::sync::mpsc::Receiver<RuntimeCommand>,
    terminate_flag: Arc<AtomicBool>,
) {
    // 1. Create QuickJS runtime + context
    let runtime = match rquickjs::Runtime::new() {
        Ok(r) => r,
        Err(e) => {
            let _ = event_tx.send(RuntimeEvent::Result {
                stored_values: request.stored_values.clone(),
                error_text: Some(format!("failed to create JS runtime: {e}")),
            });
            return;
        }
    };

    // Configure resource limits
    runtime.set_memory_limit(64 * 1024 * 1024); // 64 MB
    runtime.set_max_stack_size(512 * 1024); // 512 KB
    runtime.set_gc_threshold(4 * 1024 * 1024); // 4 MB

    // Install interrupt handler for termination support
    let term_flag = terminate_flag.clone();
    runtime.set_interrupt_handler(Some(Box::new(move || term_flag.load(Ordering::SeqCst))));

    let context = match rquickjs::Context::full(&runtime) {
        Ok(c) => c,
        Err(e) => {
            let _ = event_tx.send(RuntimeEvent::Result {
                stored_values: request.stored_values.clone(),
                error_text: Some(format!("failed to create JS context: {e}")),
            });
            return;
        }
    };

    // 2. Build shared state
    let state: SharedState = Arc::new(Mutex::new(RuntimeState {
        event_tx: event_tx.clone(),
        tool_call_id: request.tool_call_id.clone(),
        stored_values: request.stored_values.clone(),
        next_tool_call_id: 1,
        pending_tool_ids: std::collections::HashSet::new(),
        exit_requested: false,
    }));

    // 3. Install globals and evaluate source
    let eval_error = context.with(|ctx| {
        if let Err(e) = install_globals(&ctx, &request, &state) {
            return Some(e);
        }

        // Send Started event
        let _ = event_tx.send(RuntimeEvent::Started);

        // Evaluate source as script wrapped in an async IIFE for top-level await:
        //   (async () => { <user_source> })()
        let wrapped_source = format!("(async () => {{\n{}\n}})()", request.source);

        let mut options = EvalOptions::default();
        options.global = true;
        options.strict = false;
        options.backtrace_barrier = true;

        let result: Result<Value<'_>, _> = ctx.eval_with_options(wrapped_source, options);
        match result.catch(&ctx) {
            Ok(_) => None,
            Err(err) => {
                // Check for exit sentinel
                let is_exit = state.lock().map(|s| s.exit_requested).unwrap_or(false);
                if is_exit {
                    None
                } else {
                    Some(format_caught_error(&ctx, err))
                }
            }
        }
    });

    // If eval itself failed synchronously (non-exit error), send result and return
    if let Some(error_text) = eval_error {
        let stored_values = state
            .lock()
            .map(|s| s.stored_values.clone())
            .unwrap_or_default();
        let _ = event_tx.send(RuntimeEvent::Result {
            stored_values,
            error_text: Some(error_text),
        });
        return;
    }

    // Check if exit was requested during synchronous eval
    {
        let s = state.lock().unwrap();
        if s.exit_requested {
            let _ = event_tx.send(RuntimeEvent::Result {
                stored_values: s.stored_values.clone(),
                error_text: None,
            });
            return;
        }
    }

    // 4. Command loop: process tool responses and drive microtasks
    //
    // In single-threaded WASM, `command_rx.recv()` will block (WASI
    // blocking I/O), which is how we yield to the host. The service layer
    // sends ToolResponse commands through the channel, unblocking us.
    //
    // When there are no pending tool calls we skip blocking and just drain
    // any remaining microtasks.
    loop {
        // Check termination flag
        if terminate_flag.load(Ordering::SeqCst) {
            break;
        }

        // Check if we have pending tool calls that need responses
        let has_pending_tools = state
            .lock()
            .map(|s| !s.pending_tool_ids.is_empty())
            .unwrap_or(false);

        if has_pending_tools {
            // Block waiting for a command (tool response or terminate)
            match command_rx.recv() {
                Ok(RuntimeCommand::Terminate) => {
                    terminate_flag.store(true, Ordering::SeqCst);
                    break;
                }
                Ok(RuntimeCommand::ToolResponse { id, result }) => {
                    resolve_tool_response(&context, &state, &id, Ok(result));
                }
                Ok(RuntimeCommand::ToolError { id, error_text }) => {
                    resolve_tool_response(&context, &state, &id, Err(error_text));
                }
                Err(_) => break, // Channel disconnected
            }
        } else {
            // No pending tool calls — drain non-blocking commands
            loop {
                match command_rx.try_recv() {
                    Ok(RuntimeCommand::Terminate) => {
                        terminate_flag.store(true, Ordering::SeqCst);
                        break;
                    }
                    Ok(RuntimeCommand::ToolResponse { id, result }) => {
                        resolve_tool_response(&context, &state, &id, Ok(result));
                    }
                    Ok(RuntimeCommand::ToolError { id, error_text }) => {
                        resolve_tool_response(&context, &state, &id, Err(error_text));
                    }
                    Err(_) => break,
                }
            }
        }

        if terminate_flag.load(Ordering::SeqCst) {
            break;
        }

        // Drive pending microtasks / promises
        let has_pending = runtime.execute_pending_job();

        // Check if exit was requested
        {
            let s = state.lock().unwrap();
            if s.exit_requested {
                let _ = event_tx.send(RuntimeEvent::Result {
                    stored_values: s.stored_values.clone(),
                    error_text: None,
                });
                return;
            }
        }

        // Check completion: no pending jobs and no pending tool calls
        let no_pending_tools = state
            .lock()
            .map(|s| s.pending_tool_ids.is_empty())
            .unwrap_or(true);

        match has_pending {
            Ok(false) if no_pending_tools => break, // All done
            Err(_) => {
                // Runtime error during microtask execution
                let s = state.lock().unwrap();
                if s.exit_requested {
                    let _ = event_tx.send(RuntimeEvent::Result {
                        stored_values: s.stored_values.clone(),
                        error_text: None,
                    });
                    return;
                }
                break;
            }
            _ => {}
        }
    }

    // 5. Send final result
    let stored_values = state
        .lock()
        .map(|s| s.stored_values.clone())
        .unwrap_or_default();
    let _ = event_tx.send(RuntimeEvent::Result {
        stored_values,
        error_text: None,
    });
}

// ---------------------------------------------------------------------------
// Promise resolution for tool responses
// ---------------------------------------------------------------------------

fn resolve_tool_response(
    context: &rquickjs::Context,
    state: &SharedState,
    id: &str,
    response: Result<JsonValue, String>,
) {
    // Remove from pending set
    {
        let mut s = state.lock().unwrap();
        s.pending_tool_ids.remove(id);
    }

    // Resolve or reject via the JS-side __toolResolvers map
    context.with(|ctx| {
        let js_code = match response {
            Ok(ref result) => {
                let json_str = serde_json::to_string(result).unwrap_or_else(|_| "null".to_string());
                format!(
                    r#"(function() {{
    var r = globalThis.__toolResolvers && globalThis.__toolResolvers["{}"];
    if (r) {{ delete globalThis.__toolResolvers["{}"]; r.resolve(JSON.parse('{}')); }}
}})()"#,
                    id,
                    id,
                    json_str.replace('\\', "\\\\").replace('\'', "\\'")
                )
            }
            Err(ref error_text) => {
                let escaped = error_text.replace('\\', "\\\\").replace('\'', "\\'");
                format!(
                    r#"(function() {{
    var r = globalThis.__toolResolvers && globalThis.__toolResolvers["{}"];
    if (r) {{ delete globalThis.__toolResolvers["{}"]; r.reject('{}'); }}
}})()"#,
                    id, id, escaped
                )
            }
        };
        let _: Result<Value<'_>, _> = ctx.eval(js_code);
    });
}

// ---------------------------------------------------------------------------
// Global function installation
// ---------------------------------------------------------------------------

fn install_globals<'js>(
    ctx: &rquickjs::Ctx<'js>,
    request: &ExecuteRequest,
    state: &SharedState,
) -> Result<(), String> {
    let globals = ctx.globals();

    // Remove console from globalThis (matches V8 behavior)
    let _ = globals.remove::<&str>("console");

    // Install text(value) — serializes value to string, emits text content item
    {
        let state = state.clone();
        let text_inner = Function::new(ctx.clone(), move |json: String| {
            let s = state.lock().unwrap();
            let _ = s.event_tx.send(RuntimeEvent::ContentItem(
                FunctionCallOutputContentItem::InputText { text: json },
            ));
        })
        .map_err(|e| format!("failed to create __text_inner: {e}"))?;
        globals
            .set("__text_inner", text_inner)
            .map_err(|e| format!("failed to set __text_inner: {e}"))?;
        let _: Value<'_> = ctx
            .eval(
                r#"globalThis.text = function(value) {
    var s;
    if (value === undefined) s = "undefined";
    else if (value === null) s = "null";
    else if (typeof value === "string") s = value;
    else if (typeof value === "object") s = JSON.stringify(value);
    else s = String(value);
    __text_inner(s);
};
delete globalThis.__text_inner;
undefined"#,
            )
            .map_err(|e| format!("failed to install text(): {e}"))?;
    }

    // Install image(data_or_url, detail) — emits image content item
    {
        let state = state.clone();
        let image_inner =
            Function::new(ctx.clone(), move |url: String, detail: String| {
                let detail_val = match detail.as_str() {
                    "auto" => Some(ImageDetail::Auto),
                    "low" => Some(ImageDetail::Low),
                    "high" => Some(ImageDetail::High),
                    "original" => Some(ImageDetail::Original),
                    _ => None,
                };
                let s = state.lock().unwrap();
                let _ = s.event_tx.send(RuntimeEvent::ContentItem(
                    FunctionCallOutputContentItem::InputImage {
                        image_url: url,
                        detail: detail_val,
                    },
                ));
            })
            .map_err(|e| format!("failed to create __image_inner: {e}"))?;
        globals
            .set("__image_inner", image_inner)
            .map_err(|e| format!("failed to set __image_inner: {e}"))?;
        let _: Value<'_> = ctx
            .eval(
                r#"globalThis.image = function(value) {
    if (typeof value === "string") {
        __image_inner(value, "");
    } else if (value && typeof value === "object" && value.image_url) {
        __image_inner(value.image_url, value.detail || "");
    } else {
        throw new TypeError("image expects a URL string or {image_url, detail?} object");
    }
};
delete globalThis.__image_inner;
undefined"#,
            )
            .map_err(|e| format!("failed to install image(): {e}"))?;
    }

    // Install store(key, value) — saves to stored_values HashMap
    {
        let state = state.clone();
        let store_inner =
            Function::new(ctx.clone(), move |key: String, json: String| {
                let value: JsonValue =
                    serde_json::from_str(&json).unwrap_or(JsonValue::Null);
                let mut s = state.lock().unwrap();
                s.stored_values.insert(key, value);
            })
            .map_err(|e| format!("failed to create __store_inner: {e}"))?;
        globals
            .set("__store_inner", store_inner)
            .map_err(|e| format!("failed to set __store_inner: {e}"))?;
        let _: Value<'_> = ctx
            .eval(
                r#"globalThis.store = function(key, value) {
    if (typeof key !== "string") throw new TypeError("store key must be a string");
    var json = JSON.stringify(value);
    if (json === undefined) throw new TypeError("Unable to store " + JSON.stringify(key) + ". Only plain serializable objects can be stored.");
    __store_inner(key, json);
};
delete globalThis.__store_inner;
undefined"#,
            )
            .map_err(|e| format!("failed to install store(): {e}"))?;
    }

    // Install load(key) — retrieves from stored_values
    {
        let state = state.clone();
        let load_inner = Function::new(ctx.clone(), move |key: String| -> String {
            let s = state.lock().unwrap();
            match s.stored_values.get(&key) {
                Some(value) => serde_json::to_string(value).unwrap_or_else(|_| "null".to_string()),
                None => "__UNDEFINED__".to_string(),
            }
        })
        .map_err(|e| format!("failed to create __load_inner: {e}"))?;
        globals
            .set("__load_inner", load_inner)
            .map_err(|e| format!("failed to set __load_inner: {e}"))?;
        let _: Value<'_> = ctx
            .eval(
                r#"globalThis.load = function(key) {
    if (typeof key !== "string") throw new TypeError("load key must be a string");
    var json = __load_inner(key);
    if (json === "__UNDEFINED__") return undefined;
    return JSON.parse(json);
};
delete globalThis.__load_inner;
undefined"#,
            )
            .map_err(|e| format!("failed to install load(): {e}"))?;
    }

    // Install notify(text) — emits RuntimeEvent::Notify
    {
        let state = state.clone();
        let notify_inner = Function::new(ctx.clone(), move |text: String| -> rquickjs::Result<()> {
            if text.trim().is_empty() {
                return Err(rquickjs::Error::new_from_js("value", "non-empty text"));
            }
            let s = state.lock().unwrap();
            let _ = s.event_tx.send(RuntimeEvent::Notify {
                call_id: s.tool_call_id.clone(),
                text,
            });
            Ok(())
        })
        .map_err(|e| format!("failed to create __notify_inner: {e}"))?;
        globals
            .set("__notify_inner", notify_inner)
            .map_err(|e| format!("failed to set __notify_inner: {e}"))?;
        let _: Value<'_> = ctx
            .eval(
                r#"globalThis.notify = function(value) {
    var s;
    if (value === undefined) s = "undefined";
    else if (value === null) s = "null";
    else if (typeof value === "string") s = value;
    else if (typeof value === "object") s = JSON.stringify(value);
    else s = String(value);
    __notify_inner(s);
};
delete globalThis.__notify_inner;
undefined"#,
            )
            .map_err(|e| format!("failed to install notify(): {e}"))?;
    }

    // Install yield_control() — emits RuntimeEvent::YieldRequested
    {
        let state = state.clone();
        let yield_fn = Function::new(ctx.clone(), move || {
            let s = state.lock().unwrap();
            let _ = s.event_tx.send(RuntimeEvent::YieldRequested);
        })
        .map_err(|e| format!("failed to create yield_control: {e}"))?;
        globals
            .set("yield_control", yield_fn)
            .map_err(|e| format!("failed to set yield_control: {e}"))?;
    }

    // Install exit() — sets exit_requested flag and throws to unwind
    {
        let state = state.clone();
        let exit_fn = Function::new(ctx.clone(), move || -> rquickjs::Result<()> {
            {
                let mut s = state.lock().unwrap();
                s.exit_requested = true;
            }
            Err(rquickjs::Error::Exception)
        })
        .map_err(|e| format!("failed to create exit: {e}"))?;
        globals
            .set("exit", exit_fn)
            .map_err(|e| format!("failed to set exit: {e}"))?;
    }

    // Install tools object and ALL_TOOLS metadata array
    install_tool_globals(ctx, &request.enabled_tools, state)?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Tool globals: tools.<name>() and ALL_TOOLS array
// ---------------------------------------------------------------------------

fn install_tool_globals<'js>(
    ctx: &rquickjs::Ctx<'js>,
    enabled_tools: &[ToolDefinition],
    state: &SharedState,
) -> Result<(), String> {
    let globals = ctx.globals();

    // Build `tools` object
    let tools_obj =
        Object::new(ctx.clone()).map_err(|e| format!("failed to create tools object: {e}"))?;

    // Build ALL_TOOLS array
    let all_tools = rquickjs::Array::new(ctx.clone())
        .map_err(|e| format!("failed to create ALL_TOOLS array: {e}"))?;

    for (index, tool) in enabled_tools.iter().enumerate() {
        let global_name = normalize_code_mode_identifier(&tool.name);
        let tool_name = tool.name.clone();

        // Create tool function using JS-level wrapper to avoid Rust lifetime issues.
        // We create a Rust function that takes (ctx, args) → serialized JSON,
        // then wrap it in a JS async function that creates/returns the Promise.
        let state_clone = state.clone();
        let tool_name_clone = tool_name.clone();

        // The inner function: receives JSON-serialized input, sends tool call event,
        // returns a tool call ID that the JS wrapper uses.
        let inner_fn = Function::new(ctx.clone(), move |input_json: String| -> String {
            let input: Option<JsonValue> = if input_json == "__NONE__" {
                None
            } else {
                serde_json::from_str(&input_json).ok()
            };

            let mut s = state_clone.lock().unwrap();
            let id = format!("tool-{}", s.next_tool_call_id);
            s.next_tool_call_id = s.next_tool_call_id.saturating_add(1);
            s.pending_tool_ids.insert(id.clone());
            let _ = s.event_tx.send(RuntimeEvent::ToolCall {
                id: id.clone(),
                name: tool_name_clone.clone(),
                input,
            });
            id
        })
        .map_err(|e| format!("failed to create tool inner fn {}: {e}", tool.name))?;

        // Install the inner function as a hidden global
        let inner_name = format!("__tool_inner_{}", global_name);
        globals
            .set(&*inner_name, inner_fn)
            .map_err(|e| format!("failed to set inner fn: {e}"))?;

        // Create a JS wrapper function that calls the inner function and returns a Promise.
        // The Promise is stored in a global map keyed by tool call ID.
        // When a tool response arrives (via resolve_tool_response), the JS-side
        // resolver is called.
        let js_wrapper = format!(
            r#"(function(...args) {{
    var input = args.length === 0 ? "__NONE__" : JSON.stringify(args[0]);
    var id = {inner_name}(input);
    return new Promise(function(resolve, reject) {{
        if (!globalThis.__toolResolvers) globalThis.__toolResolvers = {{}};
        globalThis.__toolResolvers[id] = {{ resolve: resolve, reject: reject }};
    }});
}})"#,
            inner_name = inner_name
        );

        let func: Value<'_> = ctx
            .eval(js_wrapper)
            .map_err(|e| format!("failed to create tool wrapper for {}: {e}", tool.name))?;
        let func: Function<'_> = func
            .get()
            .map_err(|e| format!("failed to get tool function for {}: {e}", tool.name))?;

        tools_obj
            .set(&*global_name, func)
            .map_err(|e| format!("failed to set tool {}: {e}", global_name))?;

        // Build ALL_TOOLS metadata entry: { name, description }
        let meta =
            Object::new(ctx.clone()).map_err(|e| format!("failed to create ALL_TOOLS entry: {e}"))?;
        meta.set(
            "name",
            rquickjs::String::from_str(ctx.clone(), &global_name)
                .map_err(|e| format!("failed to allocate ALL_TOOLS name: {e}"))?,
        )
        .map_err(|e| format!("failed to set ALL_TOOLS name: {e}"))?;
        meta.set(
            "description",
            rquickjs::String::from_str(ctx.clone(), &tool.description)
                .map_err(|e| format!("failed to allocate ALL_TOOLS description: {e}"))?,
        )
        .map_err(|e| format!("failed to set ALL_TOOLS description: {e}"))?;
        all_tools
            .set(index, meta)
            .map_err(|e| format!("failed to append ALL_TOOLS entry: {e}"))?;
    }

    globals
        .set("tools", tools_obj)
        .map_err(|e| format!("failed to set tools global: {e}"))?;
    globals
        .set("ALL_TOOLS", all_tools)
        .map_err(|e| format!("failed to set ALL_TOOLS global: {e}"))?;

    Ok(())
}

// ---------------------------------------------------------------------------
// JSON <-> QuickJS value conversion
// ---------------------------------------------------------------------------

fn quickjs_to_json<'js>(
    ctx: &rquickjs::Ctx<'js>,
    value: &Value<'js>,
) -> rquickjs::Result<Option<JsonValue>> {
    if value.is_undefined() || value.is_null() {
        return Ok(None);
    }
    if value.is_bool() {
        return Ok(Some(JsonValue::Bool(value.as_bool().unwrap_or(false))));
    }
    if value.is_int() {
        return Ok(Some(JsonValue::Number(serde_json::Number::from(
            value.as_int().unwrap_or(0),
        ))));
    }
    if value.is_float() {
        let f = value.as_float().unwrap_or(0.0);
        if let Some(n) = serde_json::Number::from_f64(f) {
            return Ok(Some(JsonValue::Number(n)));
        }
        return Ok(Some(JsonValue::Null));
    }
    if value.is_string() {
        let s: String = value.get().unwrap_or_default();
        return Ok(Some(JsonValue::String(s)));
    }

    // For objects/arrays, use JSON.stringify then parse on the Rust side
    let json_global = ctx.globals();
    let json_obj: Object<'_> = json_global
        .get("JSON")
        .map_err(|_| rquickjs::Error::Exception)?;
    let stringify_fn: Function<'_> = json_obj
        .get("stringify")
        .map_err(|_| rquickjs::Error::Exception)?;
    let result: Value<'_> = stringify_fn
        .call((value.clone(),))
        .map_err(|_| rquickjs::Error::Exception)?;

    if result.is_undefined() {
        return Ok(None);
    }

    let json_str: String = result.get().unwrap_or_default();
    match serde_json::from_str(&json_str) {
        Ok(v) => Ok(Some(v)),
        Err(_) => Ok(None),
    }
}

fn json_to_quickjs<'js>(ctx: &rquickjs::Ctx<'js>, value: &JsonValue) -> Value<'js> {
    match value {
        JsonValue::Null => Value::new_null(ctx.clone()),
        JsonValue::Bool(b) => Value::new_bool(ctx.clone(), *b),
        JsonValue::Number(n) => {
            if let Some(i) = n.as_i64() {
                if let Ok(i32_val) = i32::try_from(i) {
                    Value::new_int(ctx.clone(), i32_val)
                } else {
                    Value::new_float(ctx.clone(), i as f64)
                }
            } else if let Some(f) = n.as_f64() {
                Value::new_float(ctx.clone(), f)
            } else {
                Value::new_null(ctx.clone())
            }
        }
        JsonValue::String(s) => rquickjs::String::from_str(ctx.clone(), s)
            .map(|s| s.into_value())
            .unwrap_or_else(|_| Value::new_null(ctx.clone())),
        JsonValue::Array(_) | JsonValue::Object(_) => {
            // Use JSON.parse for complex values
            let json_str = serde_json::to_string(value).unwrap_or_default();
            let json_global = ctx.globals();
            let json_obj: Result<Object<'_>, _> = json_global.get("JSON");
            if let Ok(json_obj) = json_obj {
                let parse_fn: Result<Function<'_>, _> = json_obj.get("parse");
                if let Ok(parse_fn) = parse_fn {
                    let result: Result<Value<'_>, _> = parse_fn.call((json_str,));
                    if let Ok(val) = result {
                        return val;
                    }
                }
            }
            Value::new_null(ctx.clone())
        }
    }
}

// ---------------------------------------------------------------------------
// Output serialization helpers
// ---------------------------------------------------------------------------

fn serialize_output_text<'js>(
    ctx: &rquickjs::Ctx<'js>,
    value: &Value<'js>,
) -> rquickjs::Result<String> {
    if value.is_undefined() {
        return Ok("undefined".to_string());
    }
    if value.is_null() {
        return Ok("null".to_string());
    }
    if value.is_string() {
        return value.get::<String>();
    }
    if value.is_bool() {
        return Ok(value.as_bool().unwrap_or(false).to_string());
    }
    if value.is_int() {
        return Ok(value.as_int().unwrap_or(0).to_string());
    }
    if value.is_float() {
        return Ok(value.as_float().unwrap_or(0.0).to_string());
    }

    // For objects/arrays, use JSON.stringify
    let json_global = ctx.globals();
    let json_obj: Object<'_> = json_global
        .get("JSON")
        .map_err(|_| rquickjs::Error::Exception)?;
    let stringify_fn: Function<'_> = json_obj
        .get("stringify")
        .map_err(|_| rquickjs::Error::Exception)?;
    let result: Value<'_> = stringify_fn
        .call((value.clone(),))
        .map_err(|_| rquickjs::Error::Exception)?;
    if result.is_undefined() {
        return Ok("undefined".to_string());
    }
    result.get::<String>()
}

fn normalize_output_image<'js>(
    ctx: &rquickjs::Ctx<'js>,
    value: &Value<'js>,
) -> rquickjs::Result<FunctionCallOutputContentItem> {
    if value.is_string() {
        let url: String = value.get()?;
        return Ok(FunctionCallOutputContentItem::InputImage {
            image_url: url,
            detail: None,
        });
    }

    if value.is_object() {
        let obj: Object<'_> = value.get()?;
        let image_url: String = obj.get("image_url").unwrap_or_default();

        if image_url.is_empty() {
            return Err(rquickjs::Error::new_from_js(
                "object",
                "image with image_url property",
            ));
        }

        let detail: Option<String> = obj.get("detail").ok();
        let detail = detail.and_then(|d| match d.as_str() {
            "auto" => Some(ImageDetail::Auto),
            "low" => Some(ImageDetail::Low),
            "high" => Some(ImageDetail::High),
            "original" => Some(ImageDetail::Original),
            _ => None,
        });

        return Ok(FunctionCallOutputContentItem::InputImage {
            image_url,
            detail,
        });
    }

    Err(rquickjs::Error::new_from_js(
        "value",
        "string URL or image object",
    ))
}

// ---------------------------------------------------------------------------
// Error formatting
// ---------------------------------------------------------------------------

fn format_caught_error<'js>(
    ctx: &rquickjs::Ctx<'js>,
    err: rquickjs::CaughtError<'js>,
) -> String {
    match err {
        rquickjs::CaughtError::Error(e) => format!("{e}"),
        rquickjs::CaughtError::Exception(exc) => {
            let msg = exc.message();
            let stack = exc.stack();
            match (msg, stack) {
                (Some(m), Some(s)) if !s.is_empty() => format!("{m}\n{s}"),
                (Some(m), _) => m,
                (None, Some(s)) if !s.is_empty() => s,
                _ => exc.to_string(),
            }
        }
        rquickjs::CaughtError::Value(val) => {
            serialize_output_text(ctx, &val).unwrap_or_else(|_| "unknown error".to_string())
        }
    }
}
