[package]
name = "codex-arg0"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[lib]
name = "codex_arg0"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1" }
codex-apply-patch = { path = "../apply-patch" }
codex-shell-escalation = { path = "../shell-escalation" }
codex-utils-home-dir = { path = "../utils/home-dir" }
dotenvy = { version = "0.15.7" }
tempfile = { version = "3.23.0" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
