[package]
name = "codex-rmcp-client"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
axum = { version = "0.8", default-features = false, features = ["http1", "tokio"] }
codex-client = { path = "../codex-client" }
codex-config = { path = "../config" }
codex-keyring-store = { path = "../../../codex-wasm/wasi-keyring-store" }
codex-protocol = { path = "../protocol" }
codex-utils-pty = { path = "../../../codex-wasm/wasi-pty" }
codex-utils-home-dir = { path = "../utils/home-dir" }
futures = { version = "0.3", default-features = false, features = ["alloc", "std"] }
oauth2 = "5"
reqwest = { path = "../../../codex-wasm/wasi-reqwest" }
rmcp = { version = "0.15.0", default-features = false, features = ["base64", "client", "macros", "schemars", "server", "transport-child-process", "transport-streamable-http-client-reqwest"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
sha2 = { version = "0.10" }
sse-stream = "0.2.1"
thiserror = { version = "2.0.17" }
tiny_http = { version = "0.12" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tracing = { version = "0.1.44", features = ["log"] }
urlencoding = { version = "2.1" }
webbrowser = { version = "1.0" }

[dev-dependencies]
codex-utils-cargo-bin = { path = "../utils/cargo-bin" }
pretty_assertions = { version = "1.4.1" }
serial_test = { version = "3.2.0" }
tempfile = { version = "3.23.0" }
