[package]
name = "codex-rmcp-client"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
codex-keyring-store = { path = "../keyring-store" }
codex-protocol = { path = "../protocol" }
codex-utils-pty = { path = "../utils/pty" }
futures = { version = "0.3", default-features = false, features = ["alloc", "std"] }
reqwest = { path = "../../../codex-wasm/wasi-reqwest" }
rmcp = { version = "0.15.0", default-features = false, features = ["base64", "client", "macros", "schemars", "server"] }
schemars = { version = "0.8.22" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
thiserror = { version = "2.0.17" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tracing = { version = "0.1.44", features = ["log"] }
webbrowser = { version = "1.0" }

[dev-dependencies]
codex-utils-cargo-bin = { path = "../utils/cargo-bin" }
pretty_assertions = { version = "1.4.1" }
serial_test = { version = "3.2.0" }
tempfile = { version = "3.23.0" }
