[package]
name = "codex-responses-api-proxy"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[lib]
name = "codex_responses_api_proxy"
path = "src/lib.rs"

[[bin]]
name = "codex-responses-api-proxy"
path = "src/main.rs"

[dependencies]
anyhow = { version = "1" }
clap = { version = "4", features = ["derive"] }
ctor = { version = "0.6.3" }
libc = { version = "0.2.182" }
reqwest = { path = "../../../codex-wasm/wasi-reqwest" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tiny_http = { version = "0.12" }
zeroize = { version = "1.8.2" }
