[package]
edition = "2024"
license = "Apache-2.0"
name = "codex-features"
version = "0.0.0"

[lib]
doctest = false
name = "codex_features"
path = "src/lib.rs"

[dependencies]
codex-login = { path = "../login" }
codex-otel = { path = "../../../codex-wasm/wasi-codex-otel" }
codex-protocol = { path = "../protocol" }
schemars = { version = "0.8.22" }
serde = { version = "1", features = ["derive"] }
toml = { version = "0.9.5" }
tracing = { version = "0.1.44", features = ["log"] }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
