[package]
name = "codex-feedback"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = { version = "1" }
codex-login = { path = "../login" }
codex-protocol = { path = "../protocol" }
tracing = { version = "0.1.44" }
tracing-subscriber = { version = "0.3.22" }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
