//! Stub module — plugin sync replaced with no-ops for wasip2.
//! Auto-generated by codex-codemod. Do not edit.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use crate::AuthManager;
use crate::config::Config;
use super::PluginsManager;

pub(crate) fn curated_plugins_repo_path(_codex_home: &Path) -> PathBuf {
    PathBuf::from("/tmp/codex-plugins")
}

pub(crate) fn read_curated_plugins_sha(_codex_home: &Path) -> Option<String> {
    None
}

pub(crate) fn sync_openai_plugins_repo(_codex_home: &Path) -> Result<String, String> {
    Err("plugin sync not available in WASM".into())
}

pub(super) fn start_startup_remote_plugin_sync_once(
    _manager: Arc<PluginsManager>,
    _codex_home: PathBuf,
    _config: Config,
    _auth_manager: Arc<AuthManager>,
) {
    // No-op in WASM
}

#[cfg(test)]
mod tests {}
