[package]
edition = "2024"
license = "Apache-2.0"
name = "codex-analytics"
version = "0.0.0"

[lib]
doctest = false
name = "codex_analytics"
path = "src/lib.rs"

[dependencies]
codex-app-server-protocol = { path = "../app-server-protocol" }
codex-git-utils = { path = "../git-utils" }
codex-login = { path = "../login" }
codex-plugin = { path = "../plugin" }
codex-protocol = { path = "../protocol" }
os_info = { path = "../../../codex-wasm/wasi-os-info" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
sha1 = { version = "0.10.6" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tracing = { version = "0.1.44", features = ["log"] }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
