[package]
edition = "2024"
license = "Apache-2.0"
name = "codex-shell-escalation"
version = "0.0.0"

[[bin]]
name = "codex-execve-wrapper"
path = "src/bin/main_execve_wrapper.rs"

[dependencies]
anyhow = { version = "1" }
async-trait = { version = "0.1.89" }
clap = { version = "4", features = ["derive"] }
codex-protocol = { path = "../protocol" }
codex-utils-absolute-path = { path = "../utils/absolute-path" }
libc = { version = "0.2.182" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
socket2 = { version = "0.6.1", features = ["all"] }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tokio-util = { path = "../../../codex-wasm/wasi-tokio-util" }
tracing = { version = "0.1.44" }
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
tempfile = { version = "3.23.0" }
