[package]
name = "codex-cli"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
build = "build.rs"

[[bin]]
name = "codex"
path = "src/main.rs"

[lib]
name = "codex_cli"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1" }
clap = { version = "4", features = ["derive"] }
clap_complete = { version = "4" }
codex-app-server = { path = "../app-server" }
codex-app-server-protocol = { path = "../app-server-protocol" }
codex-arg0 = { path = "../arg0" }
codex-utils-cli = { path = "../utils/cli" }
codex-config = { path = "../config" }
codex-core = { path = "../core" }
codex-exec-server = { path = "../../../codex-wasm/wasi-exec-server" }
codex-execpolicy = { path = "../execpolicy" }
codex-features = { path = "../features" }
codex-login = { path = "../login" }
codex-mcp = { path = "../codex-mcp" }
codex-protocol = { path = "../protocol" }
codex-rmcp-client = { path = "../../../codex-wasm/wasi-rmcp-client" }
codex-sandboxing = { path = "../sandboxing" }
codex-state = { path = "../state" }
codex-terminal-detection = { path = "../../../codex-wasm/wasi-terminal-detection" }
codex-utils-path = { path = "../utils/path-utils" }
libc = { version = "0.2.182" }
owo-colors = { version = "4.3.0" }
regex-lite = { version = "0.1.8" }
serde_json = { version = "1" }
supports-color = { version = "3.0.2" }
tempfile = { version = "3.23.0" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
toml = { version = "0.9.5" }
tracing = { version = "0.1.44" }
tracing-appender = { version = "0.2.3" }
tracing-subscriber = { version = "0.3.22" }

[dev-dependencies]
assert_cmd = { version = "2" }
assert_matches = { version = "1.5.0" }
codex-utils-cargo-bin = { path = "../utils/cargo-bin" }
predicates = { version = "3" }
pretty_assertions = { version = "1.4.1" }
