[package]
name = "codex-stdio-to-uds"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[[bin]]
name = "codex-stdio-to-uds"
path = "src/main.rs"

[lib]
name = "codex_stdio_to_uds"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1" }

[dev-dependencies]
codex-utils-cargo-bin = { path = "../utils/cargo-bin" }
pretty_assertions = { version = "1.4.1" }
tempfile = { version = "3.23.0" }
