[package]
name = "codex-network-proxy"
edition = "2024"
version = "0.0.0"
license = "Apache-2.0"

[lib]
name = "codex_network_proxy"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1" }
async-trait = { version = "0.1.89" }
clap = { version = "4", features = ["derive"] }
chrono = { version = "0.4.43" }
codex-utils-absolute-path = { path = "../utils/absolute-path" }
codex-utils-home-dir = { path = "../utils/home-dir" }
globset = { version = "0.4" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
thiserror = { version = "2.0.17" }
time = { version = "0.3.47" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tracing = { version = "0.1.44" }
url = { version = "2" }
rama-core = { version = "=0.3.0-alpha.4" }
rama-http = { version = "=0.3.0-alpha.4" }
rama-http-backend = { version = "=0.3.0-alpha.4", features = ["tls"] }
rama-net = { version = "=0.3.0-alpha.4", features = ["http", "tls"] }
rama-socks5 = { version = "=0.3.0-alpha.4" }
rama-tcp = { version = "=0.3.0-alpha.4", features = ["http"] }
rama-tls-rustls = { version = "=0.3.0-alpha.4", features = ["http"] }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
tempfile = { version = "3.23.0" }
