[package]
name = "codex-network-proxy"
edition = "2024"
version = "0.0.0"
license = "Apache-2.0"

[lib]
name = "codex_network_proxy"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1" }
async-trait = { version = "0.1.89" }
codex-utils-absolute-path = { path = "../utils/absolute-path" }
codex-utils-home-dir = { path = "../utils/home-dir" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
thiserror = { version = "2.0.17" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
tracing = { version = "0.1.44" }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
tempfile = { version = "3.23.0" }
