[package]
name = "codex-app-server-client"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[lib]
name = "codex_app_server_client"
path = "src/lib.rs"

[dependencies]
codex-app-server-protocol = { path = "../app-server-protocol" }
codex-arg0 = { path = "../arg0" }
codex-core = { path = "../core" }
codex-features = { path = "../features" }
codex-protocol = { path = "../protocol" }
futures = { version = "0.3", default-features = false , features = ["alloc"] }
serde = { version = "1" }
serde_json = { version = "1" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
toml = { version = "0.9.5" }
tracing = { version = "0.1.44" }
url = { version = "2" }

[dev-dependencies]
pretty_assertions = { version = "1.4.1" }
serde_json = { version = "1" }
tokio = { path = "../../../codex-wasm/wasi-tokio" }
